-- contracts + calendar (2026-09-26, TODO.md §3): the two tables nothing owned.
--
-- contracts: front-month / expiry / roll for the symbols we trade. CME equity index futures
-- (NQ, MNQ, ES) expire on the THIRD FRIDAY of Mar/Jun/Sep/Dec at 09:30 ET; the customary roll
-- (volume moves to the next month) is the Thursday 8 days before expiry. If the third Friday
-- is an exchange holiday the contract expires the prior business day (Juneteenth 2027 falls
-- on Fri 18 Jun 2027 — flagged in `note`). Rows are GENERATED by rule (third_friday()), so a
-- typo is impossible, but a rule is not the rulebook: verify `roll_date` against the CME
-- product calendar once per quarter and correct the row if the exchange announces otherwise.
--
-- calendar: exchange holidays / early closes (CME Globex equity index, times in CT as CME
-- publishes them) and scheduled economic releases (ET). Rule-derived rows carry
-- source='rule'; hand-entered rows carry the source URL. Missing kinds (CPI/PPI/retail
-- sales) are deliberately NOT guessed — add them from the BLS schedule when needed.
--
-- Readers: nothing yet. Intended: grid/dashboard "next roll" warning, the executor's
-- news blackout (today hard-coded 08:30/10:00/14:00/14:30 in orb_strategy.hpp) and
-- session_stats (holiday-shortened sessions).

CREATE OR REPLACE FUNCTION third_friday(p_year int, p_month int) RETURNS date
LANGUAGE sql IMMUTABLE AS $$
  SELECT (make_date(p_year, p_month, 1)
          + ((5 - extract(dow FROM make_date(p_year, p_month, 1))::int + 7) % 7)   -- first Friday
          + 14)::date                                                            -- third Friday
$$;

CREATE TABLE IF NOT EXISTS contracts (
    symbol         text NOT NULL,          -- NQ | MNQ | ES
    contract       text NOT NULL,          -- NQZ6 (CME month code + year digit)
    month_code     char(1) NOT NULL,       -- H M U Z
    expiry_date    date NOT NULL,          -- third Friday 09:30 ET (or prior business day)
    roll_date      date NOT NULL,          -- Thursday 8 days before expiry (volume roll)
    first_trade    date,                   -- when this contract becomes front month (= prior roll_date)
    note           text,
    source         text NOT NULL DEFAULT 'rule',
    PRIMARY KEY (symbol, contract)
);

-- Generate Dec 2026 .. Sep 2027 for NQ / MNQ / ES.
INSERT INTO contracts (symbol, contract, month_code, expiry_date, roll_date, first_trade, note)
SELECT s.symbol,
       s.symbol || m.code || right(m.yr::text, 1),
       m.code,
       CASE WHEN third_friday(m.yr, m.mon) = DATE '2027-06-18'
            THEN DATE '2027-06-17' ELSE third_friday(m.yr, m.mon) END,
       third_friday(m.yr, m.mon) - 8,
       lag(third_friday(m.yr, m.mon) - 8) OVER (PARTITION BY s.symbol ORDER BY m.yr, m.mon),
       CASE WHEN third_friday(m.yr, m.mon) = DATE '2027-06-18'
            THEN 'third Friday is Juneteenth (exchange holiday) — expires Thu 17 Jun 2027; VERIFY with CME'
            ELSE NULL END
FROM (VALUES ('NQ'), ('MNQ'), ('ES')) AS s(symbol)
CROSS JOIN (VALUES (2026, 9, 'U'), (2026, 12, 'Z'), (2027, 3, 'H'), (2027, 6, 'M'), (2027, 9, 'U')) AS m(yr, mon, code)
ON CONFLICT (symbol, contract) DO NOTHING;

-- The front month on a given date (roll-date aware).
CREATE OR REPLACE FUNCTION front_month(p_symbol text, p_date date DEFAULT current_date) RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT contract FROM contracts
  WHERE symbol = p_symbol AND roll_date > p_date
  ORDER BY expiry_date LIMIT 1
$$;

CREATE TABLE IF NOT EXISTS calendar (
    day         date NOT NULL,
    kind        text NOT NULL,      -- holiday | early_close | fomc | nfp
    label       text NOT NULL,
    time_et     time,               -- release time (ET) for economic events; NULL for holidays
    close_ct    time,               -- early-close time in CT as CME states it (NULL = closed all day)
    note        text,
    source      text NOT NULL,
    PRIMARY KEY (day, kind)
);

-- CME Globex equity index holiday schedule, Q4 2026 – Q3 2027 (CME publishes these as CT).
-- Full-day closures and early closes; the 17:00 CT Sunday-style reopen after each is normal.
INSERT INTO calendar (day, kind, label, close_ct, note, source) VALUES
 ('2026-11-26', 'early_close', 'Thanksgiving Day',        '12:00', 'trading halts 12:00 CT, reopens 17:00 CT',      'CME holiday calendar 2026 — verify'),
 ('2026-11-27', 'early_close', 'Day after Thanksgiving',  '12:15', 'early close 12:15 CT',                          'CME holiday calendar 2026 — verify'),
 ('2026-12-24', 'early_close', 'Christmas Eve',           '12:15', 'early close 12:15 CT',                          'CME holiday calendar 2026 — verify'),
 ('2026-12-25', 'holiday',     'Christmas Day',           NULL,    'closed',                                        'CME holiday calendar 2026 — verify'),
 ('2027-01-01', 'holiday',     'New Year''s Day',         NULL,    'closed',                                        'CME holiday calendar 2027 — verify'),
 ('2027-01-18', 'early_close', 'Martin Luther King Day',  '12:00', 'halts 12:00 CT, reopens 17:00 CT',              'CME holiday calendar 2027 — verify'),
 ('2027-02-15', 'early_close', 'Presidents'' Day',        '12:00', 'halts 12:00 CT, reopens 17:00 CT',              'CME holiday calendar 2027 — verify'),
 ('2027-03-26', 'holiday',     'Good Friday',             NULL,    'closed (8:30 ET NFP may still print)',          'CME holiday calendar 2027 — verify'),
 ('2027-05-31', 'early_close', 'Memorial Day',            '12:00', 'halts 12:00 CT, reopens 17:00 CT',              'CME holiday calendar 2027 — verify'),
 ('2027-06-18', 'early_close', 'Juneteenth',              '12:00', 'halts 12:00 CT; also the June expiry Friday',   'CME holiday calendar 2027 — verify'),
 ('2027-07-05', 'early_close', 'Independence Day (obs.)', '12:00', 'halts 12:00 CT, reopens 17:00 CT',              'CME holiday calendar 2027 — verify'),
 ('2027-09-06', 'early_close', 'Labor Day',               '12:00', 'halts 12:00 CT, reopens 17:00 CT',              'CME holiday calendar 2027 — verify')
ON CONFLICT (day, kind) DO NOTHING;

-- FOMC decision days (second day of each meeting; statement 14:00 ET, press conference 14:30).
INSERT INTO calendar (day, kind, label, time_et, source) VALUES
 ('2026-10-28', 'fomc', 'FOMC decision', '14:00', 'federalreserve.gov 2026 meeting schedule'),
 ('2026-12-09', 'fomc', 'FOMC decision', '14:00', 'federalreserve.gov 2026 meeting schedule')
ON CONFLICT (day, kind) DO NOTHING;

-- Non-farm payrolls: first Friday of the month at 08:30 ET (rule; BLS shifts it when the
-- first Friday is a holiday or falls on the 1st/2nd — Jan 2027 is the 8th for that reason).
INSERT INTO calendar (day, kind, label, time_et, note, source)
SELECT d, 'nfp', 'Non-farm payrolls', '08:30',
       CASE WHEN d = DATE '2027-01-01' THEN 'BLS moves this to Jan 8 (holiday) — corrected below' END,
       'rule: first Friday'
FROM (SELECT (make_date(y, m, 1) + ((5 - extract(dow FROM make_date(y, m, 1))::int + 7) % 7))::date AS d
      FROM (VALUES (2026,10),(2026,11),(2026,12),(2027,2),(2027,3),(2027,4)) AS ym(y, m)) f
ON CONFLICT (day, kind) DO NOTHING;
INSERT INTO calendar (day, kind, label, time_et, note, source) VALUES
 ('2027-01-08', 'nfp', 'Non-farm payrolls', '08:30', 'first Friday is New Year''s Day', 'rule: first Friday (holiday-shifted)')
ON CONFLICT (day, kind) DO NOTHING;

-- Convenience: everything that matters in the next N days.
CREATE OR REPLACE FUNCTION upcoming_events(p_days int DEFAULT 14)
RETURNS TABLE (day date, kind text, label text, time_et time, close_ct time, note text)
LANGUAGE sql STABLE AS $$
  SELECT day, kind, label, time_et, close_ct, note FROM calendar
  WHERE day BETWEEN current_date AND current_date + p_days
  UNION ALL
  SELECT roll_date, 'roll', symbol || ' roll → ' || contract, NULL, NULL,
         'front month becomes ' || contract || ' (expiry ' || expiry_date || ')'
  FROM contracts WHERE roll_date BETWEEN current_date AND current_date + p_days
  ORDER BY 1, 2
$$;
